Update stale.yml to latest v9
dotnet/docs-aspire pull request #1557
Opened 2024-08-24 14:41 UTC by kzu

The commit pointed is already in v9. 

See https://github.com/actions/stale/commit/28ca1036281a5e5922ead5184a1bbf96e5fc984e

2024-08-24 17:14 UTC, IEvangelist requested changes
Could you please instead use the commit sha?

2024-08-26 12:16 UTC, IEvangelist commented
I'm going to close this PR as we only accept commit shas.

2024-08-26 12:16 UTC, closed without merging

2024-08-26 15:26 UTC, kzu commented
That's inconsistent with other dotnet repos, i.e. https://github.com/dotnet/sdk/blob/main/.github/workflows/stale.yml#L29
Seems like this should be a common thing across all org repos 🤷‍♀️

2024-08-26 15:42 UTC, IEvangelist commented
Yes, I agree. We're working on the consistent part now.