Make it easier to onboard with VS Code.
dotnet/docs-aspire pull request #1861
Opened 2024-10-16 19:03 UTC by IEvangelist

## Summary

- Use steps for troubleshooting guide.
- Add more context to VS Code self-signed cert bits.
- Add link.
- Add images.

Describe your changes here.

Fixes #1851

2024-10-16 20:12 UTC, claudiaregio commented
looks gooooooood

2024-10-21 21:43 UTC, adegeo requested changes
Two bugs to fix

2024-10-21 21:43 UTC, adegeo commented on docs/troubleshooting/untrusted-localhost-certificate.md
> +  ```
The alerts and code snippets aren't rendering correctly on the published page. You must indent to the first character numbered item's text to get it to actually appear under the item.
Correct way:
```markdown
1. ABC
...The ... at the start here show you that you must have 3 spaces to align properly.
```
Personally I use this to make sure it's 4 spaces indented on child content, which makes it easy to <kbd>TAB</kbd> position content:

```markdown
01. ABC
....This is four spaces in
```

This is what's on the published page:
![image](https://github.com/user-attachments/assets/b12e85bb-d184-4e42-bca8-90c670710745)

2024-10-22 01:07 UTC, adegeo approved these changes

2024-10-22 01:07 UTC, merged